server:
  port: ${PORT:8085}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1

        - id: measurement-service
          uri: lb://MEASUREMENT-SERVICE
          predicates:
            - Path=/measurement/**
          filters:
            - StripPrefix=1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://eureka-server-vzyy.onrender.com/eureka/
  instance:
    prefer-ip-address: false
    non-secure-port: ${PORT:8085}
    instance-id: ${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: health,info