server:
  port: ${PORT:8084}

spring:
  config:
    import: optional:classpath:application-secrets.yml

  application:
    name: measurement-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://eureka-server-vzyy.onrender.com/eureka/
  instance:
    prefer-ip-address: false
    non-secure-port: ${PORT:8084}
    instance-id: ${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: health,info